# Generated by Django 4.0.2 on 2022-02-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cep',
            name='cep',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
