# Generated by Django 4.0.2 on 2022-02-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cep_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cep',
            name='bairro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cep',
            name='complemento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cep',
            name='ddd',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='cep',
            name='gia',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='cep',
            name='ibge',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cep',
            name='localidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cep',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cep',
            name='siafi',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='cep',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
